# Site settings
title: "Abhishek's Dev Hub"
description: "Exploring technology, open-source, and scalable software development."
author: "Abhishek"
email: "your-email@example.com"  # Optional, replace with your email if needed

# Theme settings
remote_theme: jekyll/minima  # You can change this to any other Jekyll theme you like
show_excerpts: true  # Show post summaries on the homepage
paginate: 5  # Number of posts per page

# GitHub Pages settings
baseurl: ""  # Leave this empty if deploying at username.github.io
url: "https://k-r-abhishek.github.io/skills-github-pages"  # Replace with your GitHub Pages URL

# Markdown and plugins
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation and layout
header_pages:
  - index.md  # Ensures index.md is used as the homepage
  - about.md  # Add if you have an About page
  - projects.md  # Add if you have a Projects page

# Social links (optional)
social:
  github: your-github-username
  linkedin: your-linkedin-username
  twitter: your-twitter-handle

# Exclude unnecessary files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
